from typing import Any, Callable, Optional, Protocol, runtime_checkable

from iris_vector_graph.result import IVGResult


@runtime_checkable
class GraphStore(Protocol):
    def get_nodes(self, node_ids: list, properties: Optional[list] = None) -> IVGResult: ...
    def get_node_labels(self, node_ids: list) -> IVGResult: ...
    def query_nodes(self, label_filter: Optional[str] = None, property_filters: Optional[dict] = None,
                    return_properties: Optional[list] = None, limit: int = 0) -> IVGResult: ...
    def write_nodes(self, nodes: list) -> IVGResult: ...
    def write_edges(self, edges: list) -> IVGResult: ...
    def delete_nodes(self, node_ids: list) -> IVGResult: ...
    def delete_edges(self, edges: list) -> IVGResult: ...
    def execute_sql(self, sql: str, params: list, read_only: bool = True) -> IVGResult: ...
    def execute_transaction(self, stmts: list, params_list: list) -> IVGResult: ...
    # Spec 227: `graph` scopes the traversal. Keyword-only and defaulting to None
    # (the default graph `''`), so a 3.2.0 positional call still works and no value
    # means "every graph" — an unscoped BFS is how spec 227 found the leak.
    def execute_bfs(self, source_id: str, predicates: list, max_hops: int,
                    direction: str, max_results: int, *,
                    graph: Optional[str] = None) -> IVGResult: ...
    def execute_shortest_path(self, source_id: str, target_id: str, predicates: list,
                               max_hops: int, direction: str, find_all: bool) -> IVGResult: ...
    def execute_weighted_shortest_path(self, source_id: str, target_id: str,
                                        weight_property: str, max_hops: int) -> IVGResult: ...
    # `bidirectional` / `reverse_edge_weight` are part of the interface because a store
    # that ignores them answers the wrong question: forward-only scores for a caller who
    # asked for reverse traversal, with no error to say so. A store that cannot honour
    # them should raise, not approximate — the engine then drops to its Python fallback.
    #
    # `graph` (spec 231) is sent only for a named graph, so a store written before 4.0.1
    # still serves the default graph; one that does not accept it raises `TypeError` and
    # the engine falls back rather than scoring the default graph instead.
    def execute_ppr(self, seed_ids: list, damping: float, max_iterations: int,
                    bidirectional: bool = False,
                    reverse_edge_weight: float = 1.0, *,
                    graph: Optional[str] = None) -> IVGResult: ...
    def execute_pagerank(self, damping: float, max_iterations: int) -> IVGResult: ...
    def execute_wcc(self) -> IVGResult: ...
    def execute_cdlp(self, max_iterations: int) -> IVGResult: ...
    def execute_subgraph(self, seed_ids: list, k_hops: int, edge_types: list,
                         max_nodes: int) -> IVGResult: ...
    # Spec 227: `graph` and `model_key` select the routed embedding table. Both are
    # keyword-only so a 3.2.0 positional call fails instead of binding a graph to
    # `label_filter`, and both default to None, which means the default graph `''` —
    # there is no value that means every graph (FR-004).
    def execute_knn_vec(self, query_vector: list, k: int,
                        label_filter: Optional[str], *,
                        graph: Optional[str] = None,
                        model_key: Optional[str] = None) -> IVGResult: ...
    def write_temporal_edge(self, source_id: str, predicate: str, target_id: str,
                             timestamp: int, weight: float = 1.0, attrs: Optional[dict] = None,
                             upsert: bool = False,
                             suppress_reverse_index: bool = False,
                             mode: str = "",
                             graph: Optional[str] = None) -> IVGResult: ...
    def delete_temporal_edge(self, source_id: str, predicate: str, target_id: str,
                             timestamp: int,
                             graph: Optional[str] = None) -> bool: ...
    def bulk_write_temporal_edges(self, edges: list, upsert: bool = False,
                                   suppress_reverse_index: bool = False,
                                   graph: Optional[str] = None,
                                   mode: str = "") -> IVGResult: ...
    def purge_bucket_range(self, bucket_start: int, bucket_end: int,
                           graph: Optional[str] = None) -> int: ...
    def purge_raw_before(self, ts_end: int, ts_start: int = 0,
                         graph: Optional[str] = None) -> int: ...
    def intern_label_set(self, attrs_json: str) -> str: ...
    def resolve_label_set(self, hash_hex: str) -> str: ...
    def execute_temporal_window_query(self, source_id: str, predicate: str,
                                       ts_start: int, ts_end: int,
                                       direction: str = "out",
                                       graph: Optional[str] = None) -> IVGResult: ...
    def execute_temporal_cypher(self, source_id: str, predicates: list, ts_start: int,
                                 ts_end: int, direction: str, max_hops: int,
                                 graph: Optional[str] = None) -> IVGResult: ...
    def get_temporal_aggregate(self, source_id: str, predicate: str, metric: str,
                               ts_start: int, ts_end: int,
                               graph: Optional[str] = None) -> IVGResult: ...
    def get_node_count(self, label: Optional[str] = None) -> IVGResult: ...
    def get_edge_count(self, predicate: Optional[str] = None) -> IVGResult: ...
    def get_labels(self) -> IVGResult: ...
    def get_relationship_types(self) -> IVGResult: ...
    def list_indexes(self) -> IVGResult: ...
    def server_info(self) -> IVGResult: ...

    def execute_degree_centrality(self, direction: str, predicate: str,
                                   top_k: int) -> IVGResult: ...
    def execute_betweenness(self, sample_size: int, direction: str, max_hops: int,
                             top_k: int, mem_budget_mb: int,
                             progress_callback: Optional[Callable[[int, int], None]] = None) -> IVGResult: ...
    def execute_closeness(self, formula: str, direction: str, max_hops: int, top_k: int,
                           progress_callback: Optional[Callable[[int, int], None]] = None) -> IVGResult: ...
    def execute_eigenvector(self, max_iter: int, tol: float, top_k: int,
                             progress_callback: Optional[Callable[[int, int], None]] = None) -> IVGResult: ...

    def execute_leiden(self, max_levels: int, gamma: float, tol: float, top_k: int,
                       mem_budget_mb: int, random_seed: Optional[int] = None,
                       progress_callback: Optional[Callable[[int, int], None]] = None) -> IVGResult: ...
    def execute_triangle_count(self, top_k: int,
                                progress_callback: Optional[Callable[[int, int], None]] = None) -> IVGResult: ...
    def execute_scc(self, top_k: int,
                    progress_callback: Optional[Callable[[int, int], None]] = None) -> IVGResult: ...
    def execute_k_core(self, top_k: int,
                       progress_callback: Optional[Callable[[int, int], None]] = None) -> IVGResult: ...

    def capabilities(self) -> dict: ...
    def close(self) -> None: ...
