from typing import Any, Optional, Protocol, runtime_checkable

from iris_vector_graph.result import IVGResult


@runtime_checkable
class GraphStore(Protocol):
    def get_nodes(self, node_ids: list, properties: Optional[list] = None) -> IVGResult: ...
    def get_node_labels(self, node_ids: list) -> IVGResult: ...
    def query_nodes(self, label_filter: Optional[str] = None, property_filters: Optional[dict] = None,
                    return_properties: Optional[list] = None, limit: int = 0) -> IVGResult: ...
    def write_nodes(self, nodes: list) -> IVGResult: ...
    def write_edges(self, edges: list) -> IVGResult: ...
    def delete_nodes(self, node_ids: list) -> IVGResult: ...
    def delete_edges(self, edges: list) -> IVGResult: ...
    def execute_sql(self, sql: str, params: list, read_only: bool = True) -> IVGResult: ...
    def execute_transaction(self, stmts: list, params_list: list) -> IVGResult: ...
    def execute_bfs(self, source_id: str, predicates: list, max_hops: int,
                    direction: str, max_results: int) -> IVGResult: ...
    def execute_shortest_path(self, source_id: str, target_id: str, predicates: list,
                               max_hops: int, direction: str, find_all: bool) -> IVGResult: ...
    def execute_weighted_shortest_path(self, source_id: str, target_id: str,
                                        weight_property: str, max_hops: int) -> IVGResult: ...
    def execute_ppr(self, seed_ids: list, damping: float, max_iterations: int) -> IVGResult: ...
    def execute_pagerank(self, damping: float, max_iterations: int) -> IVGResult: ...
    def execute_wcc(self) -> IVGResult: ...
    def execute_cdlp(self, max_iterations: int) -> IVGResult: ...
    def execute_subgraph(self, seed_ids: list, k_hops: int, edge_types: list,
                         max_nodes: int) -> IVGResult: ...
    def execute_knn_vec(self, query_vector: list, k: int,
                        label_filter: Optional[str]) -> IVGResult: ...
    def write_temporal_edge(self, source_id: str, predicate: str, target_id: str,
                             timestamp: int, weight: float = 1.0, attrs: Optional[dict] = None,
                             upsert: bool = False) -> IVGResult: ...
    def bulk_write_temporal_edges(self, edges: list, upsert: bool = False) -> IVGResult: ...
    def execute_temporal_window_query(self, source_id: str, predicate: str,
                                       ts_start: int, ts_end: int,
                                       direction: str = "out") -> IVGResult: ...
    def execute_temporal_cypher(self, source_id: str, predicates: list, ts_start: int,
                                 ts_end: int, direction: str, max_hops: int) -> IVGResult: ...
    def get_temporal_aggregate(self, source_id: str, predicate: str, metric: str,
                               ts_start: int, ts_end: int) -> IVGResult: ...
    def get_node_count(self, label: Optional[str] = None) -> IVGResult: ...
    def get_edge_count(self, predicate: Optional[str] = None) -> IVGResult: ...
    def get_labels(self) -> IVGResult: ...
    def get_relationship_types(self) -> IVGResult: ...
    def list_indexes(self) -> IVGResult: ...
    def server_info(self) -> IVGResult: ...
    def capabilities(self) -> dict: ...
    def close(self) -> None: ...
